export const DefaultValue = {
    BLANK: '',
    DOT: '.',
    UNDER_HYPHEN: '_',
    HYPHEN: '-',
    SPACE: ' ',
    ZERO: 0,
    COMMA: ',',
    COMMA_BLANK: ', ',
    SLASH: '/',
    TEN: 10,
    FIVE: 5,
    HUNDRED: 100,
    THOUSAND: 1000,
    QUESTION: '?',
    COLON: ':',
    MAX_INTEGER: 2147483647,
}
