name: Deploy to Oracle Server

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '22'

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Build project
              run: pnpm start:build

            - name: Deploy to Oracle Server
              env:
                  HOST: ${{ secrets.ORACLE_HOST }}
                  USERNAME: ${{ secrets.ORACLE_USERNAME }}
                  SSH_KEY: ${{ secrets.ORACLE_SSH_KEY }}
              run: |
                  # SSH 키 저장 및 권한 설정
                  mkdir -p ~/.ssh
                  echo "${SSH_KEY}" > ~/.ssh/id_rsa  
                  chmod 600 ~/.ssh/id_rsa

                  # 원격 서버에 배포 디렉토리 생성
                  ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${USERNAME}@${HOST} "mkdir -p /home/${USERNAME}/app"

                  # 서버로 파일 전송 및 배포
                  rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./.next/ ${USERNAME}@${HOST}:/home/${USERNAME}/app/
                  rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" package.json ${USERNAME}@${HOST}:/home/${USERNAME}/app/
                  rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" node_modules/ ${USERNAME}@${HOST}:/home/${USERNAME}/app/

                  # 보안상 키 삭제
                  rm -f ~/.ssh/id_rsa
