name: Deploy to Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: |
                  npm install -g pnpm
                  pnpm install --frozen-lockfile

            - name: Deploy to Server
              uses: appleboy/scp-action@v0.1.0
              with:
                  host: ${{ secrets.ORACLE_HOST }}
                  username: ${{ secrets.ORACLE_USERNAME }}
                  key: ${{ secrets.ORACLE_SSH_KEY }}
                  key_path: ${{ secrets.ORACLE_SSH_KEY_PATH }}
                  source: '.'
                  target: ${{ secrets.DEPLOY_PATH }}

            - name: SSH Connect and Build
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.ORACLE_HOST }}
                  username: ${{ secrets.ORACLE_USERNAME }}
                  key: ${{ secrets.ORACLE_SSH_KEY }}
                  key_path: ${{ secrets.ORACLE_SSH_KEY_PATH }}
                  script: |
                      cd ${{ secrets.DEPLOY_PATH }}
                      pnpm install --frozen-lockfile
                      pnpm start:build
                      pnpm start:prod
