name: Deploy Travel-hub Frontend to Server

on:
    push:
        branches:
            - main

jobs:
    # Docker Image Build
    build:
        runs-on: ubuntu-latest
        outputs:
            image_tag: ${{ steps.tag.outputs.image_tag }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set Docker Image Tag
              id: tag
              run: echo "image_tag=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build Docker Image
              run: |
                  docker buildx create --use
                  docker buildx build --platform linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/travel-hub-fe:${{ steps.tag.outputs.image_tag }} --push .
                  docker tag ${{ secrets.DOCKER_USERNAME }}/travel-hub-fe:${{ steps.tag.outputs.image_tag }} ${{ secrets.DOCKER_USERNAME }}/travel-hub-fe:latest

    # Push Docker Image to Docker Hub
    push:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Docker Login (Docker Hub)
              run: |
                  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Push Docker Image to Docker Hub
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/travel-hub-fe:${{ needs.build.outputs.image_tag }}
                  docker push ${{ secrets.DOCKER_USERNAME }}/travel-hub-fe:latest

    # Deploy to Server
    deploy:
        needs: [build, push]
        runs-on: ubuntu-latest
        steps:
            - name: SSH Connect and Deploy to Server
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.ORACLE_HOST }}
                  username: ${{ secrets.ORACLE_USERNAME }}
                  key: ${{ secrets.ORACLE_SSH_KEY }}
                  script: |
                      # Stop and Remove Existing Container
                      docker stop travel-hub-fe || true
                      docker rm travel-hub-fe || true

                      # Pull Latest Docker Image
                      docker pull ${{ secrets.DOCKER_USERNAME }}/travel-hub-fe:${{ needs.build.outputs.image_tag }}

                      # Run New Container
                      docker run --platform linux/arm64 -d --name travel-hub-fe -p 9599:3000 ${{ secrets.DOCKER_USERNAME }}/travel-hub-fe:${{ needs.build.outputs.image_tag }}
