name: Deploy to Oracle Server

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '22'

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Build project
              run: pnpm start:build

            - name: Upload build artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: build-output
                  path: .next/

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Download build artifacts
              uses: actions/download-artifact@v2
              with:
                  name: build-output
                  path: .next/

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.ORACLE_SSH_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.ORACLE_HOST }} >> ~/.ssh/known_hosts

            - name: Deploy to Oracle Server
              env:
                  HOST: ${{ secrets.ORACLE_HOST }}
                  USERNAME: ${{ secrets.ORACLE_USERNAME }}
              run: |
                  ssh -i ~/.ssh/id_rsa ${USERNAME}@${HOST} "sudo chown -R ${USERNAME}:${USERNAME} /home/travelhub/app/"
                  rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./.next/ ${USERNAME}@${HOST}:/home/travelhub/app/

            - name: Upload SSH key
              uses: actions/upload-artifact@v2
              with:
                  name: ssh-key
                  path: ~/.ssh/
                  retention-days: 1

    pm2-setup:
        needs: deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Download SSH key
              uses: actions/download-artifact@v2
              with:
                  name: ssh-key
                  path: ~/.ssh/

            - name: Set SSH key permissions
              run: chmod 600 ~/.ssh/id_rsa

            - name: Setup PM2 Configuration
              env:
                  HOST: ${{ secrets.ORACLE_HOST }}
                  USERNAME: ${{ secrets.ORACLE_USERNAME }}
              run: |
                  scp -i ~/.ssh/id_rsa ecosystem.config.js ${USERNAME}@${HOST}:/home/travelhub/app/

            - name: Start PM2 Service
              env:
                  HOST: ${{ secrets.ORACLE_HOST }}
                  USERNAME: ${{ secrets.ORACLE_USERNAME }}
              run: |
                  ssh -i ~/.ssh/id_rsa ${USERNAME}@${HOST} "
                    cd /home/travelhub/app && \
                    pnpm install && \
                    pm2 reload ecosystem.config.js --update-env && \
                    pm2 save
                  "

            - name: Cleanup SSH key
              if: always()
              run: rm -rf ~/.ssh
