name: Deploy to Oracle Server

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '22'

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Build project
              run: pnpm start:build

            - name: Deploy to Oracle Server
              env:
                  HOST: ${{ secrets.ORACLE_HOST }}
                  USERNAME: ${{ secrets.ORACLE_USERNAME }}
                  SSH_KEY: ${{ secrets.ORACLE_SSH_KEY }}
              run: |
                  # SSH 키 저장 및 권한 설정
                  mkdir -p ~/.ssh
                  echo "${SSH_KEY}" > ~/.ssh/id_rsa  
                  chmod 600 ~/.ssh/id_rsa

                  # 필요한 파일들 압축 후 전송
                  tar -czvf deploy.tar.gz .next public package.json pnpm-lock.yaml
                  scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no deploy.tar.gz ${USERNAME}@${HOST}:/home/travelhub/

                  # 서버에서 압축 해제 후 실행
                  ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${USERNAME}@${HOST} "
                    cd /home/travelhub/ && \
                    rm -rf app && mkdir app && \
                    tar -xzvf deploy.tar.gz -C app && \
                    cd app && \
                    npm install -g pnpm && \
                    pnpm install --prod && \
                    pm2 stop travel-hub-front || true && \
                    pm2 start pnpm --name 'travel-hub-front' -- start:prod && \
                    pm2 save
                  "

                  # 보안상 SSH 키 삭제
                  rm -f ~/.ssh/id_rsa
