name: Deploy to Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: |
                  npm install -g pnpm
                  pnpm install --frozen-lockfile

            - name: Deploy to Server
              uses: appleboy/scp-action@v0.1.0
              with:
                  host: ${{ secrets.ORACLE_HOST }}
                  username: ${{ secrets.ORACLE_USERNAME }}
                  key: ${{ secrets.ORACLE_SSH_KEY }}
                  source: '.'
                  target: ${{ secrets.DEPLOY_PATH }}

            - name: SSH Connect and Build
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.ORACLE_HOST }}
                  username: ${{ secrets.ORACLE_USERNAME }}
                  key: ${{ secrets.ORACLE_SSH_KEY }}
                  script: |
                      cd ${{ secrets.DEPLOY_PATH }}
                      npm install -g pm2
                      pnpm install --frozen-lockfile
                      pnpm start:build

                      if pm2 describe travel-hub-front > /dev/null 2>&1; then
                          echo "Start reload travel-hub-front"
                          pm2 reload ecosystem.config.js --update-env
                      else
                          echo "Start new process travel-hub-front"
                          pm2 start ecosystem.config.js
                      fi
                      pm2 save
